[package]
name = "json2nix"
version = "0.1.0"
description = "Library to convert JSON to a Nix expression"
edition.workspace = true
authors.workspace = true

[dependencies]
serde_json = { workspace = true }
